variable "gcp_project" {
  type        = string
  description = "GCP project ID."
}

variable "ns1_apikey" {
  type        = string
  description = "API Key for NS1 DNS provider"
}

variable "k8s_context" {
  type        = string
  description = "The config name of the Kubernetes cluster. Auto-generated by 'gcloud container clusters get-credentials'."
}

variable "k8s_namespace" {
  type        = string
  description = "The k8s namespace for all docs"
}

variable "nginx_ingress_loadbalancer" {
  type        = string
  description = "K8s LoadBalancer of NGINX Ingress."
}

variable "dns_env_subdomain" {
  type        = string
  description = "Subdomain of environment"
}

variable "dns_domain" {
  type        = string
  description = "Domain to publish docs under"
}

variable "redoc_image" {
  type        = string
  description = "The docker image used to display the swagger specs"
}

variable "k8s_image_pull_secret_name" {
  type        = string
  description = "The name of the k8s secret used to pull images from a docker registry"
  default     = "regcred"
}

variable "dns_zone" {
  type        = string
  description = "DNS zone."
  default     = "blockdaemon.com"
}

variable "gcp_bucket_name" {
  type        = string
  description = "Name of the gcp bucket that holds the openrpc specs"
}
