stages:
  - check

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://localhost:2375
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  BUCKET_NAME: blockdaemon-sdk-bpm-docs
  BUCKET_PATH: "gs://${BUCKET_NAME}"
  SOURCE: https://raw.githubusercontent.com/Blockdaemon/bpm-sdk/master/swagger.yaml


services:
- docker:dind

check:
  image: golangci/golangci-lint:v1.17.1
  stage: check
  script:
    - golangci-lint run --enable gofmt ./...

deploy_swagger_to_bucket:
  image: google/cloud-sdk:latest
  stage: .post
  script:
    - gcloud auth activate-service-account --key-file ${TERRAFORM_SA}
    - curl ${SOURCE} | gsutil -h "Cache-Control:must-revalidate, max-age=600" cp - ${BUCKET_PATH}/bpm-sdk-swagger.yaml
  when: always
  only:
    - master
