stages:
  - check

variables:
  BUCKET_NAME: blockdaemon-sdk-bpm-docs
  BUCKET_PATH: "gs://${BUCKET_NAME}"

check:
  image: golangci/golangci-lint:v1.27
  stage: check
  script:
    - golangci-lint run --enable gofmt ./...

deploy_swagger_to_bucket:
  image: google/cloud-sdk:latest
  stage: .post
  script:
    - gcloud auth activate-service-account --key-file ${TERRAFORM_SA}
    - cat swagger.yaml | gsutil -h "Cache-Control:must-revalidate, max-age=600" cp - ${BUCKET_PATH}/bpm-sdk-swagger.yaml
  when: manual
